spring:
    redis:
      database: 0
      host: 192.168.184.129
      jedis:
        pool:
          max-active: -1
          max-idle: -1
          min-idle: 8
          max-wait: 50000ms
      timeout: 50000ms
    cache:
      type: redis